# Collector Configuration
# Replace with your own values

storage:
    # Replace output directory with the location where you want
    # the output json file to be stored
    data_dir: <output_directory>
    # Replace <MDEVS-data> with the prefix of choice 
    # and don't forget to remove the <>
    data_file_prefix: <MDEVS-data>

secure:
    # Replace <token> with the Slack API token
    slack_group_token: "<token>"
