# Collector Configuration
# Replace with your own values

storage:
    data_dir: <output_directory>
    data_file_prefix: <MDEVS-data>

secure:
    # Replace <token> with the Slack API token
    slack_group_token: "<token>"
